#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc wm -O DP-2 HDMI-0
bspc monitor HDMI-0 -d 10 11 12 13 14 15 16 17 18 19
bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 2
bspc config window_gap 12

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config top_padding 20
bpsc config left_padding 0

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a kitty state=floating focus=on follow=on center=true rectangle=1280x720+0+0
